'use strict';
const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const {WebSocketServer}=require('ws');
const {Pool}=require('pg');
const nodemailer=require('nodemailer');
const {OAuth2Client}=require('google-auth-library');
const rawPhase=Number(process.env.PHASE_MS||90000); const PHASE_MS=Number.isFinite(rawPhase)?Math.min(1800000,Math.max(15000,rawPhase)):90000;
const rawPort=Number(process.env.PORT||8787); const PORT=Number.isInteger(rawPort)&&rawPort>=1&&rawPort<=65535?rawPort:8787; const MAX_ROOM=14, MIN_PLAYERS=4, MAX_TEXT=500;
const PUBLIC=path.join(__dirname,'public');const rooms=new Map();const ROOM_IDLE_MS=6*60*60*1000;const usedInvites=new Set();
const configured=(process.env.INVITE_CODES||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);const invites=new Set(configured);
const ADMIN_KEY=process.env.ADMIN_KEY||'';
const SESSION_COOKIE='cosa_admin';
const SESSION_MS=7*24*60*60*1000;
const RESET_MS=30*60*1000;
const GOOGLE_CLIENT_ID=process.env.GOOGLE_CLIENT_ID||'';
const GOOGLE_CLIENT_SECRET=process.env.GOOGLE_CLIENT_SECRET||'';
const GOOGLE_REDIRECT_URI=process.env.GOOGLE_REDIRECT_URI||'';
const oauthClient=GOOGLE_CLIENT_ID?new OAuth2Client(GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI||undefined):null;
const smtp=(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS)?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null;
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5,idleTimeoutMillis:30000,connectionTimeoutMillis:8000}):null;
if(pool)pool.on('error',err=>console.error('PostgreSQL pool error:',err.message));
async function db(q,params=[]){if(!pool)return null;return pool.query(q,params)}
function cleanEmail(v){return String(v||'').trim().toLowerCase().slice(0,254)}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function b64url(buf){return Buffer.from(buf).toString('base64url')}
function tokenHash(token){return crypto.createHash('sha256').update(token).digest('hex')}
function cookieToken(req){const m=String(req.headers.cookie||'').match(/(?:^|;\s*)cosa_admin=([^;]+)/);return m?decodeURIComponent(m[1]):''}
function hashPassword(password){return new Promise((resolve,reject)=>{const salt=crypto.randomBytes(16);crypto.scrypt(String(password),salt,64,(err,key)=>{if(err)return reject(err);resolve('scrypt$'+salt.toString('base64url')+'$'+key.toString('base64url'))})})}
function verifyPassword(password,stored){try{const [kind,salt,key]=String(stored||'').split('$');if(kind!=='scrypt'||!salt||!key)return false;return crypto.timingSafeEqual(Buffer.from(key,'base64url'),crypto.scryptSync(String(password),Buffer.from(salt,'base64url'),64))}catch{return false}}
function setCookie(res,name,value,maxAge){res.setHeader('Set-Cookie',`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=${Math.max(0,Math.floor(maxAge/1000))}`)}
async function adminFromRequest(req){if(!pool)return null;const token=cookieToken(req);if(!token)return null;const {rows}=await db('SELECT a.id,a.email,a.name,a.google_sub,a.socials,s.expires_at FROM admin_sessions s JOIN admins a ON a.id=s.admin_id WHERE s.token_hash=$1 AND s.expires_at>NOW()',[tokenHash(token)]);return rows[0]||null}
async function createAdminSession(res,adminId){const token=b64url(crypto.randomBytes(32));await db('INSERT INTO admin_sessions(token_hash,admin_id,expires_at) VALUES($1,$2,NOW()+INTERVAL \'7 days\')',[tokenHash(token),adminId]);setCookie(res,SESSION_COOKIE,token,SESSION_MS)}
async function sendResetEmail(admin,resetUrl){if(!smtp)throw new Error('Email service is not configured');await smtp.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:admin.email,subject:'COSA NOSTRA — Reset your admin password',text:`A password reset was requested for your COSA NOSTRA administrator account.\n\nOpen this link within 30 minutes:\n${resetUrl}\n\nIf you did not request this, you can ignore this email.`})}

async function initDb(){if(!pool)return;await db(`CREATE TABLE IF NOT EXISTS invites(code TEXT PRIMARY KEY, used_at TIMESTAMPTZ); CREATE TABLE IF NOT EXISTS game_history(id BIGSERIAL PRIMARY KEY, room_id TEXT NOT NULL, started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), ended_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), winner TEXT, players JSONB NOT NULL DEFAULT '[]'::jsonb); CREATE TABLE IF NOT EXISTS admins(id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL DEFAULT 'Administrator',password_hash TEXT,google_sub TEXT UNIQUE,socials JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS admin_sessions(token_hash TEXT PRIMARY KEY,admin_id BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL); CREATE TABLE IF NOT EXISTS admin_reset_tokens(token_hash TEXT PRIMARY KEY,admin_id BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ);`);const seeds=[
{email:process.env.NATASHA_ADMIN_EMAIL,name:process.env.NATASHA_ADMIN_NAME||'Natasha',password:process.env.NATASHA_ADMIN_PASSWORD,socials:{instagram:process.env.NATASHA_ADMIN_INSTAGRAM||'',facebook:process.env.NATASHA_ADMIN_FACEBOOK||'',tiktok:process.env.NATASHA_ADMIN_TIKTOK||'',x:process.env.NATASHA_ADMIN_X||''}},
{email:process.env.PEACE_ADMIN_EMAIL,name:process.env.PEACE_ADMIN_NAME||'Peace',password:process.env.PEACE_ADMIN_PASSWORD,socials:{instagram:process.env.PEACE_ADMIN_INSTAGRAM||'',facebook:process.env.PEACE_ADMIN_FACEBOOK||'',tiktok:process.env.PEACE_ADMIN_TIKTOK||'',x:process.env.PEACE_ADMIN_X||''}}
];
for(const seed of seeds){if(seed.email&&seed.password){const email=cleanEmail(seed.email);const hash=await hashPassword(seed.password);await db(`INSERT INTO admins(email,name,password_hash,socials) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name,password_hash=EXCLUDED.password_hash,updated_at=NOW()`,[email,seed.name,hash,JSON.stringify(seed.socials)]);}}}
async function loadInvites(){if(!pool)return;for(const code of configured)await saveInvite(code);const {rows}=await db('SELECT code FROM invites WHERE used_at IS NULL');for(const x of rows)invites.add(x.code)}
async function markInviteUsed(code){if(pool)await db('UPDATE invites SET used_at=NOW() WHERE code=$1',[code])}
async function saveInvite(code){if(pool)await db('INSERT INTO invites(code) VALUES($1) ON CONFLICT DO NOTHING',[code])}
async function saveHistory(r){if(!pool)return;const players=[...r.players.values()].map(x=>({name:x.name,username:x.username,age:x.age,country:x.country,state:x.state,gender:x.gender,pronouns:x.pronouns,alive:x.alive,role:x.role,archetype:x.story?.archetype,publicClue:x.story?.publicClue}));await db('INSERT INTO game_history(room_id,winner,players) VALUES($1,$2,$3)',[r.id,r.winner,JSON.stringify(players)])}
function clean(v,n=MAX_TEXT){return String(v??'').replace(/[\u0000-\u001f<>]/g,'').trim().slice(0,n)}
function id(){return crypto.randomBytes(8).toString('hex')}
function send(ws,o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o))}
function broadcast(r,o){for(const p of r.players.values())send(p.ws,o)}
function capRoomLogs(r){if(r.chat.length>200)r.chat.splice(0,r.chat.length-200);if(r.log.length>100)r.log.splice(0,r.log.length-100)}
const ARCHETYPES=['The Detective','The Socialite','The Drifter','The Fixer','The Heiress','The Insider','The Gambler','The Night Courier'];
const LOCATIONS=['the Velvet Room','the old train station','the riverside club','the rain-soaked alley','the Grand Hotel','the midnight diner'];
const OBJECTS=['a silver lighter','a torn photograph','a brass key','a red scarf','a marked playing card','a sealed envelope'];
const MOTIVES=['money','revenge','silence','loyalty','jealousy','a hidden debt'];
function pick(arr,n){let x=0;for(const c of String(n||''))x=(x+c.charCodeAt(0))%arr.length;return arr[x]}
function makeStory(p){const seed=p.username||p.name;const arch=p.archetype||pick(ARCHETYPES,seed);const loc=pick(LOCATIONS,seed+'l');const obj=pick(OBJECTS,seed+'o');const mot=pick(MOTIVES,seed+'m');return {archetype:arch,publicStory:`You were seen near ${loc} carrying ${obj}. Nobody knows whether you were protecting someone or hiding something.`,publicClue:`A witness remembers ${obj} at ${loc}. The trail may point toward a motive of ${mot}.`,privateSecret:`You privately suspect the ${mot} thread is more important than it appears. Keep this to yourself.`,privateSuspicion:`Watch the players who seem unusually connected to ${loc}.`}}

function publicPlayer(p){return {id:p.id,username:p.username,alive:p.alive,archetype:p.story?.archetype||'The Unknown',publicStory:p.story?.publicStory||'',publicClue:p.story?.publicClue||''}}
function stateFor(r,p){
 const players=[...r.players.values()].map(publicPlayer); const me=r.players.get(p.id);
 const privateData={id:me.id,role:me.role||null,alive:me.alive,story:me.story||null};
 if(me.role==='mafia') privateData.nightTargets=players.filter(x=>x.alive&&x.id!==me.id).map(x=>({id:x.id,username:x.username}));
 if(me.role==='nurse') privateData.nightTargets=players.filter(x=>x.alive).map(x=>({id:x.id,username:x.username}));
 return {type:'state',room:{id:r.id,started:r.started,phase:r.phase,day:r.day,endsAt:r.endsAt,hostId:r.hostId,minPlayers:MIN_PLAYERS,maxPlayers:MAX_ROOM},players,me:privateData,chat:r.chat.slice(-80),winner:r.winner||null,log:r.log.slice(-30)};
}
function pushState(r){capRoomLogs(r);for(const p of r.players.values())send(p.ws,stateFor(r,p))}
function alive(r){return [...r.players.values()].filter(p=>p.alive)}
function checkWin(r){const a=alive(r),m=a.filter(p=>p.role==='mafia').length,t=a.length-m;if(m===0)return 'civilians';if(m>=t)return 'mafia';return null}
function endGame(r,w){if(r.phase==='ended')return;r.winner=w;r.started=false;r.phase='ended';r.endsAt=0;const label=w==='mafia'?'The Mafia':w==='civilians'?'The civilians':'The table';r.log.push(`${label} ${w==='cancelled'?'closed the game.':'won.'}`);saveHistory(r).catch(err=>console.error('History save failed:',err.message));pushState(r)}
function beginPhase(r,phase){r.phase=phase;r.endsAt=Date.now()+PHASE_MS;r.votes=new Map();r.mafiaTarget=null;r.nurseTarget=null;r.log.push(phase==='night'?`Night ${r.day+1} begins.`:`Day ${r.day} begins.`);pushState(r)}
function resolveNight(r){const target=r.mafiaTarget,save=r.nurseTarget;if(target){const p=r.players.get(target);if(p&&p.alive&&target!==save){p.alive=false;r.log.push(`${p.username} was found dead at dawn.`)}}const w=checkWin(r);if(w)return endGame(r,w);r.day++;beginPhase(r,'day')}
function resolveVote(r){const counts=new Map();for(const v of r.votes.values())counts.set(v,(counts.get(v)||0)+1);let top=0,candidates=[];for(const [pid,n] of counts){if(n>top){top=n;candidates=[pid]}else if(n===top)candidates.push(pid)}if(top&&candidates.length===1){const p=r.players.get(candidates[0]);if(p&&p.alive){p.alive=false;r.log.push(`${p.username} was voted out.`)}}else r.log.push('The vote ended in a deadlock.');const w=checkWin(r);if(w)return endGame(r,w);beginPhase(r,'night')}
function touch(r){r.lastActivity=Date.now()}
function tick(r){if(!r.started)return;if(Date.now()<r.endsAt)return;if(r.phase==='night')resolveNight(r);else if(r.phase==='day')resolveVote(r)}
setInterval(()=>{const now=Date.now();for(const [key,r] of rooms){if(!r.players.size||(now-r.lastActivity>ROOM_IDLE_MS)){for(const p of r.players.values())try{p.ws.close(1001,'Room expired')}catch{}rooms.delete(key);continue}tick(r)}},1000).unref?.();
function joinRoom(ws,msg){const roomId=clean(msg.room,30).toUpperCase()||crypto.randomBytes(3).toString('hex').toUpperCase();const code=clean(msg.invite,40).toUpperCase();if(!code||!invites.has(code)||usedInvites.has(code))return send(ws,{type:'error',message:'Invalid or already used invitation code.'});let r=rooms.get(roomId);if(!r){r={id:roomId,hostId:null,players:new Map(),chat:[],log:[],lastActivity:Date.now(),started:false,phase:'lobby',day:0,endsAt:0,votes:new Map(),winner:null,mafiaTarget:null,nurseTarget:null};rooms.set(roomId,r)}if(r.players.size>=MAX_ROOM)return send(ws,{type:'error',message:'This room is full.'});if(r.started)return send(ws,{type:'error',message:'The game has already started.'});const profile=msg.profile&&typeof msg.profile==='object'?msg.profile:{};const name=clean(profile.name,50),username=clean(profile.username,30),age=clean(profile.age,3),state=clean(profile.state,40),country=clean(profile.country,40),gender=clean(profile.gender,20),pronouns=clean(profile.pronouns,20),archetype=clean(profile.archetype,40);if(!name||!username||!age||!state||!country||!gender||!pronouns||!archetype)return send(ws,{type:'error',message:'Complete your character profile before entering the table.'});const p={ws,id:id(),name,username,age,state,country,gender,pronouns,archetype,alive:true,role:null};p.story=makeStory(p);r.players.set(p.id,p);touch(r);if(!r.hostId)r.hostId=p.id;usedInvites.add(code);invites.delete(code);markInviteUsed(code).catch(err=>console.error('Invite update failed:',err.message));ws.player=p;ws.room=r;send(ws,{type:'joined',playerId:p.id,room:r.id});broadcast(r,{type:'system',message:`@${p.username} joined the table.`});pushState(r)}
function startGame(r,p){if(r.hostId!==p.id)return send(p.ws,{type:'error',message:'Only the room host can start the game.'});if(r.players.size<MIN_PLAYERS)return send(p.ws,{type:'error',message:`You need at least ${MIN_PLAYERS} players.`});const ps=[...r.players.values()];const roles=Array(ps.length-2).fill('civilian').concat(['mafia','nurse']);for(let i=roles.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[roles[i],roles[j]]=[roles[j],roles[i]]}ps.forEach((x,i)=>{x.role=roles[i];x.alive=true});r.started=true;r.day=1;r.winner=null;r.log.push('The table is sealed. Roles have been dealt privately.');beginPhase(r,'night')}
function handle(ws,msg){if(!msg||typeof msg!=='object')return; if(msg.type==='join')return joinRoom(ws,msg);const p=ws.player,r=ws.room;if(!p||!r)return send(ws,{type:'error',message:'Join a room first.'});if(msg.type==='chat'){if(!p.alive)return;const text=clean(msg.text);if(!text)return;touch(r);r.chat.push({id:id(),name:p.username,text,at:Date.now()});capRoomLogs(r);broadcast(r,{type:'chat',message:{name:p.username,text,at:Date.now()}});return}if(msg.type==='start'){touch(r);return startGame(r,p)}if(msg.type==='nightAction'){if(!r.started||r.phase!=='night'||!p.alive)return;touch(r);if(p.role==='mafia'){const t=clean(msg.target,40);if(r.players.has(t)&&r.players.get(t).alive&&t!==p.id)r.mafiaTarget=t}if(p.role==='nurse'){const t=clean(msg.target,40);if(r.players.has(t)&&r.players.get(t).alive)r.nurseTarget=t}send(p.ws,{type:'notice',message:'Your night action is locked in.'});return}if(msg.type==='vote'){if(!r.started||r.phase!=='day'||!p.alive)return;touch(r);const t=clean(msg.target,40);if(r.players.has(t)&&r.players.get(t).alive&&t!==p.id)r.votes.set(p.id,t);send(p.ws,{type:'notice',message:'Your vote is locked in.'});return}}

async function readJson(req,max=12000){return new Promise((resolve,reject)=>{let body='';req.on('data',d=>{body+=d;if(body.length>max){reject(new Error('too large'));req.destroy()}});req.on('end',()=>{try{resolve(JSON.parse(body||'{}'))}catch{reject(new Error('bad json'))}});req.on('error',reject)})}
function adminJson(res,status,obj){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj))}

const server=http.createServer(async (req,res)=>{const u=(req.url||'/').split('?')[0];if(u==='/health'){res.writeHead(200,{'content-type':'text/plain'});return res.end('ok\n')}
if(u==='/auth/google'&&req.method==='GET'){if(!oauthClient)return adminJson(res,503,{error:'Google sign-in is not configured.'});const state=b64url(crypto.randomBytes(24));const authUrl=oauthClient.generateAuthUrl({access_type:'offline',scope:['openid','email','profile'],state,prompt:'select_account'});setCookie(res,'cosa_oauth',state,10*60*1000);res.writeHead(302,{Location:authUrl});return res.end()}
if(u==='/auth/google/callback'&&req.method==='GET'){try{if(!oauthClient)throw new Error('Google sign-in is not configured');const q=new URL(req.url,'http://localhost');const state=q.searchParams.get('state')||'',code=q.searchParams.get('code')||'';const cookies=String(req.headers.cookie||'');const normal=cookies.match(/(?:^|;\s*)cosa_oauth=([^;]+)/);const linking=cookies.match(/(?:^|;\s*)cosa_oauth_link=([^;]+)/);const isLink=!!linking;if(!state||!(isLink?decodeURIComponent(linking[1])===state:normal&&decodeURIComponent(normal[1])===state))throw new Error('Invalid sign-in state');const {tokens}=await oauthClient.getToken(code);const ticket=await oauthClient.verifyIdToken({idToken:tokens.id_token,audience:GOOGLE_CLIENT_ID});const payload=ticket.getPayload();const email=cleanEmail(payload.email);if(!payload.email_verified||!validEmail(email))throw new Error('Google account email is not verified');if(isLink){const admin=await adminFromRequest(req);if(!admin)throw new Error('Your administrator session expired. Sign in again.');const taken=await db('SELECT id FROM admins WHERE google_sub=$1 AND id<>$2 LIMIT 1',[payload.sub,admin.id]);if(taken.rows[0])throw new Error('That Google account is already linked to another administrator.');await db('UPDATE admins SET google_sub=$1,updated_at=NOW() WHERE id=$2',[payload.sub,admin.id]);res.writeHead(302,{Location:'/admin?linked=google'});return res.end()}let {rows}=await db('SELECT * FROM admins WHERE google_sub=$1 OR email=$2 LIMIT 1',[payload.sub,email]);let admin=rows[0];if(!admin)throw new Error('This Google account is not linked to a COSA NOSTRA administrator. Ask an existing administrator to link it first.');if(!admin.google_sub)await db('UPDATE admins SET google_sub=$1,updated_at=NOW() WHERE id=$2',[payload.sub,admin.id]);await createAdminSession(res,admin.id);res.writeHead(302,{Location:'/admin'});return res.end()}catch(e){res.writeHead(302,{Location:'/admin?error='+encodeURIComponent(e.message)});return res.end()}}
if(u==='/api/admin/login'&&req.method==='POST'){try{if(!pool)return adminJson(res,503,{error:'Database is required for admin accounts.'});const x=await readJson(req);const email=cleanEmail(x.email);const password=String(x.password||'');if(!validEmail(email)||password.length<1)return adminJson(res,400,{error:'Enter your email and password.'});const {rows}=await db('SELECT * FROM admins WHERE email=$1 LIMIT 1',[email]);const admin=rows[0];if(!admin||!admin.password_hash||!verifyPassword(password,admin.password_hash))return adminJson(res,401,{error:'Incorrect email or password.'});await createAdminSession(res,admin.id);return adminJson(res,200,{ok:true})}catch(e){return adminJson(res,500,{error:'Unable to sign in.'})}}
if(u==='/api/admin/logout'&&req.method==='POST'){if(pool){const t=cookieToken(req);if(t)await db('DELETE FROM admin_sessions WHERE token_hash=$1',[tokenHash(t)])}setCookie(res,SESSION_COOKIE,'',0);return adminJson(res,200,{ok:true})}
if(u==='/api/admin/me'&&req.method==='GET'){const a=await adminFromRequest(req);if(!a)return adminJson(res,401,{error:'Not signed in'});return adminJson(res,200,{id:a.id,email:a.email,name:a.name,googleLinked:!!a.google_sub,socials:a.socials||{}})}
if(u==='/api/admin/players'&&req.method==='GET'){const a=await adminFromRequest(req);if(!a)return adminJson(res,401,{error:'Not signed in'});const roomsOut=[...rooms.values()].filter(r=>r.players.size).map(r=>({roomId:r.id,started:r.started,phase:r.phase,day:r.day,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,username:p.username,age:p.age,state:p.state,country:p.country,gender:p.gender,pronouns:p.pronouns,alive:p.alive,role:p.role||null,archetype:p.story?.archetype||'The Unknown'}))}));return adminJson(res,200,{rooms:roomsOut})}
if(u==='/api/admin/profile'&&req.method==='PATCH'){const a=await adminFromRequest(req);if(!a)return adminJson(res,401,{error:'Not signed in'});try{const x=await readJson(req);const name=clean(x.name,80)||a.name;const socials={instagram:clean(x.instagram,200),facebook:clean(x.facebook,200),tiktok:clean(x.tiktok,200),x:clean(x.x,200),snapchat:clean(x.snapchat,200)};await db('UPDATE admins SET name=$1,socials=$2,updated_at=NOW() WHERE id=$3',[name,JSON.stringify(socials),a.id]);return adminJson(res,200,{ok:true,name,socials})}catch{return adminJson(res,400,{error:'Invalid profile data.'})}}
if(u==='/api/admin/link-google'&&req.method==='POST'){const a=await adminFromRequest(req);if(!a)return adminJson(res,401,{error:'Not signed in'});if(!oauthClient)return adminJson(res,503,{error:'Google sign-in is not configured.'});const state=b64url(crypto.randomBytes(24));setCookie(res,'cosa_oauth_link',state,10*60*1000);const authUrl=oauthClient.generateAuthUrl({access_type:'offline',scope:['openid','email','profile'],state,prompt:'select_account',login_hint:a.email});return adminJson(res,200,{url:authUrl})}
if(u==='/api/admin/forgot-password'&&req.method==='POST'){try{if(!pool)return adminJson(res,200,{ok:true,message:'If that email is registered, a reset message will be sent.'});const x=await readJson(req);const email=cleanEmail(x.email);const {rows}=await db('SELECT * FROM admins WHERE email=$1 LIMIT 1',[email]);if(rows[0]&&smtp){const token=b64url(crypto.randomBytes(32));await db('DELETE FROM admin_reset_tokens WHERE admin_id=$1',[rows[0].id]);await db('INSERT INTO admin_reset_tokens(token_hash,admin_id,expires_at) VALUES($1,$2,NOW()+INTERVAL \'30 minutes\')',[tokenHash(token),rows[0].id]);const base=process.env.APP_URL||`http://${req.headers.host}`;await sendResetEmail(rows[0],`${base}/admin?reset=${encodeURIComponent(token)}`)}return adminJson(res,200,{ok:true,message:'If that email is registered, a reset message will be sent.'})}catch(e){return adminJson(res,200,{ok:true,message:'If that email is registered, a reset message will be sent.'})}}
if(u==='/api/admin/reset-password'&&req.method==='POST'){try{if(!pool)return adminJson(res,503,{error:'Database is required.'});const x=await readJson(req);const token=String(x.token||'');const password=String(x.password||'');if(password.length<10)return adminJson(res,400,{error:'Use a password of at least 10 characters.'});const {rows}=await db('SELECT admin_id FROM admin_reset_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW()',[tokenHash(token)]);if(!rows[0])return adminJson(res,400,{error:'That reset link is invalid or expired.'});const hash=await hashPassword(password);await db('UPDATE admins SET password_hash=$1,updated_at=NOW() WHERE id=$2',[hash,rows[0].admin_id]);await db('UPDATE admin_reset_tokens SET used_at=NOW() WHERE token_hash=$1',[tokenHash(token)]);await db('DELETE FROM admin_sessions WHERE admin_id=$1',[rows[0].admin_id]);return adminJson(res,200,{ok:true})}catch{return adminJson(res,500,{error:'Unable to reset password.'})}}

if(u==='/api/rooms'){const list=[...rooms.values()].filter(r=>r.players.size).map(r=>({id:r.id,players:r.players.size,max:MAX_ROOM,started:r.started}));res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify(list))}if(u==='/api/admin/invites'&&req.method==='POST'){let body='';let tooBig=false;req.on('data',d=>{if((body.length+d.length)>10000){tooBig=true;req.destroy();return}body+=d});req.on('end',async()=>{if(tooBig)return;try{const x=JSON.parse(body);if(!ADMIN_KEY||x.key!==ADMIN_KEY){res.writeHead(401);return res.end('Unauthorized')}const count=Math.min(100,Math.max(1,Number(x.count)||1));const out=[];for(let i=0;i<count;i++){let c=crypto.randomBytes(5).toString('hex').toUpperCase();while(invites.has(c)||usedInvites.has(c))c=crypto.randomBytes(5).toString('hex').toUpperCase();invites.add(c);out.push(c)}if(pool)await Promise.all(out.map(saveInvite));res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify({codes:out}))}catch(e){console.error('Invite generation failed:',e.message);res.writeHead(500);res.end('Could not create invitations')}});return}let file=u==='/'||u==='/index.html'?'index.html':u==='/game'||u==='/game.html'?'game.html':u==='/admin'?'admin.html':null;if(!file){res.writeHead(404);return res.end('Not found')}fs.readFile(path.join(PUBLIC,file),(e,b)=>{if(e){res.writeHead(500);return res.end('Server error')}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-cache','x-content-type-options':'nosniff'});res.end(b)})});
server.requestTimeout=15000;server.headersTimeout=10000;server.keepAliveTimeout=5000;
const wss=new WebSocketServer({server,maxPayload:12000});wss.on('connection',ws=>{ws.on('message',raw=>{try{handle(ws,JSON.parse(raw.toString()))}catch(e){send(ws,{type:'error',message:'Invalid message.'})}});ws.on('close',()=>{const p=ws.player,r=ws.room;if(!p||!r)return;r.players.delete(p.id);touch(r);broadcast(r,{type:'system',message:`@${p.username} left the table.`});if(r.hostId===p.id)r.hostId=r.players.keys().next().value||null;if(!r.players.size)rooms.delete(r.id);else if(r.started&&r.players.size<MIN_PLAYERS)endGame(r,'cancelled');else pushState(r)})});
async function boot(){try{await initDb();await loadInvites()}catch(err){console.error('Database unavailable; continuing without persistence:',err.message)}server.listen(PORT,'0.0.0.0',()=>console.log(`COSA NOSTRA listening on ${PORT} (phase ${PHASE_MS}ms)`))}boot().catch(err=>{console.error('Startup failed',err);process.exit(1)});
async function shutdown(){for(const ws of wss.clients)try{ws.close(1001,'Server shutting down')}catch{}await new Promise(resolve=>server.close(resolve));if(pool)await pool.end().catch(()=>{});process.exit(0)}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);;
